### ISSUE TITLE
Calling the encoding function

### ISSUE THREAD

**Issue by cadupont23** [AmirAlavi/blog-comments#5]
Hello, I was wondering how to simply encode some new data (after fitting the model to training data). I am not sure how to call the encode function that you have built.

**Comment by AmirAlavi** [comment]
Sorry to ask you to do this, but could you please ask this question as a comment on issue #4 ? That is how the blog commenting is intended to be used. That way it will be visible on the blog for others to see in case they have they same question, Currently, it's unlikely anyone will find this. Once you ask it there, I'll respond there. Thank you!
