### ISSUE TITLE
LSTM

### ISSUE THREAD

**Issue by l0d0v1c** [AmirAlavi/blog-comments#6]
Brilliant and useful. Do you plan to do same object with LSTM autoencoders? VAE? GANAE?

**Comment by AmirAlavi** [comment]
Hi @l0d0v1c , thanks for the interest! Which project are you referring to? (this repo hosts comment threads for all of my blog posts, each post has it's own issue created for commenting).

If you are referring to the tied autoencoder project, I haven't explicitly made those objects. If I ever do, I will post them here, but it's not likely that I will attempt those any time soon. However, I hope that using my implementation as a guide will help others implement those other problems.

Please let me know if there's any further questions or issues.
